# Generated by Django 5.0.3 on 2024-03-25 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='named_url',
            field=models.CharField(blank=True, help_text='Named url from your urls.py file', max_length=255, verbose_name='Named URL'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, help_text='Named url from your urls.py file', max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu'),
        ),
    ]
