# Generated by Django 5.0.3 on 2024-03-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menuitem_data_alter_menuitem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
